blank_issues_enabled: false
contact_links:
  - name: Question / usage help
    url: https://github.com/fion-private/ha-stundenplan/discussions
    about: Ask a question or get help using the integration.
